stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "nothing to build"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - cd ..
    - ./do_tests
    - echo "done testing"