stages:
  - tests_MacOS
  - test
build:
  stage: tests_MacOS
  script:
    - echo "nothing to build"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - ./do_tests
    - echo "done testing"

