stages:
  - pages
  - build
  - test

image: alpine

pages:
  script:
    - apk update && apk add doxygen
    - doxygen docs/Doxyfile.in
    - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master


build:
  stage: build
  script:
    - echo "nothing to build"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - cd ..
    - ./do_tests
    - echo "done testing"