stages:
  - test_single_header
  - test

test_single_header:
  stage: test_single_header
  script:
    - cd tests/
    - bash build_tests_for_single_header_flippy
    - cd cmake-build-default
    - ./flippy_test
    - echo "done testing"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - cd ..
    - ./do_tests
    - echo "done testing"