stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - echo "nothing to build"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - cd ..
    - ./do_tests
    - echo "done testing"

make-badge:
  stage: deploy
  script:
    - version=$(cat VERSION)
    - echo ${CI_PROJECT_ID}
    - version_badge_id=$(curl --header "PRIVATE-TOKEN:${API_TOKEN}" https://gitlab.tudelft.nl/api/v4/projects/${CI_PROJECT_ID}/badges | jq -c 'map(select(.name | contains("version")))[0].id')
    - echo $version_badge_id
    - curl --request PUT --header "PRIVATE-TOKEN:${API_TOKEN}" --data "image_url=https://img.shields.io/badge/version-${version}-blue" https://gitlab.tudelft.nl/api/v4/projects/${CI_PROJECT_ID}/badges/${version_badge_id}
