stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - echo "nothing to build"

test:
  stage: test
  script:
    - cd tests/
    - bash build_tests
    - cd cmake-build-default
    - ./flippy_test
    - cd ..
    - ./do_tests
    - echo "done testing"

make-badge:
  stage: deploy
  script:
    - version=$(cat VERSION)
    - curl --request PUT --header "PRIVATE-TOKEN:${API_TOKEN}" --data "image_url=https://img.shields.io/badge/version-${version}-blue" https://gitlab.tudelft.nl/idema-group/flippy/badges/%{default_branch}/version.svg
