#! /bin/bash
cmakeDir="cmake-build-default"
reportDir=${cmakeDir}/CMakeFiles/flippy_test.dir
cd ${cmakeDir} || exit
ctest
cd ..
lcov --zerocounters
lcov --base-directory . --directory ${reportDir} -c -o test.info
lcov --remove test.info "/Library/*" -o test.info # remove output for external libraries
lcov --remove test.info "/usr/include/*" -o test.info # remove output for external libraries
lcov --remove test.info "*/flippy/tests*" -o test.info # remove output for external libraries
lcov --remove test.info "*/flippy/flippy/external*" -o test.info # remove output for external libraries
lcov --summary test.info
#genhtml test.info --output-directory=res
#open res/index.html
