name: clang on linux test suite

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_call:

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: install clang-18
          run: sudo apt install clang-18
        - name: install Ninja
          run: sudo apt install Ninja
        - name: install Cmake
          run: sudo apt install cmake
        - name: test
          run: |
            cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-18
            cmake --build build -j 6 --target tests/all
            echo "done testing"
