name: linux test suite

on:
  push:
   branches:
     - master

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: install gcc-11
          run: sudo apt install g++-11
        - name: test
          run: |
            echo 'testing'
            cd tests/
            bash build_tests_without_coverage
            cd cmake-build-default
            ls
            ./flippy_test
            echo "done testing"
