name: Run Test Suite

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  test_single_header:
    runs-on: ubuntu-latest


    steps:
      - name: test_single_header
        run: echo 'testing'
