name: Run Test Suite

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  test_single_header:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test_single_header
        run: |
          echo 'testing'
          cd tests/
          bash build_tests_for_single_header_flippy
          cd cmake-build-default
          ./flippy_test
          echo 'done testing'

  test:
      runs-on: self-hosted
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: test
          run: |
            echo 'testing'
            cd tests/
            bash build_tests
            cd cmake-build-default
            ./flippy_test
            cd ..
            ./do_tests
            echo "done testing"
