name: minGW on windows test suite

on:
  push:
   branches:
     - master

jobs:
  test:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Set up MinGW
          uses: egor-tensin/setup-mingw@v2
          with:
            platform: x64
        - name: test
          run: |
            echo 'testing'
            which g++
            which g++11
            which g++-10
            which g++-11
            cd tests/
            bash create_cmake_dir
            cd cmake-build-default || exit 1
            cmake -D CMAKE_CXX_COMPILER=i686-w64-mingw64-g++ -S .. -B .
            make
            ./flippy_test.exe
            echo "done testing"
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
